// Generated by gencpp from file giskard_msgs/UpdateWorldRequest.msg
// DO NOT EDIT!


#ifndef GISKARD_MSGS_MESSAGE_UPDATEWORLDREQUEST_H
#define GISKARD_MSGS_MESSAGE_UPDATEWORLDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <giskard_msgs/WorldBody.h>
#include <geometry_msgs/PoseStamped.h>

namespace giskard_msgs
{
template <class ContainerAllocator>
struct UpdateWorldRequest_
{
  typedef UpdateWorldRequest_<ContainerAllocator> Type;

  UpdateWorldRequest_()
    : operation(0)
    , body()
    , rigidly_attached(false)
    , pose()  {
    }
  UpdateWorldRequest_(const ContainerAllocator& _alloc)
    : operation(0)
    , body(_alloc)
    , rigidly_attached(false)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _operation_type;
  _operation_type operation;

   typedef  ::giskard_msgs::WorldBody_<ContainerAllocator>  _body_type;
  _body_type body;

   typedef uint8_t _rigidly_attached_type;
  _rigidly_attached_type rigidly_attached;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;



  enum {
    UNDEFINED = 0u,
    ADD = 1u,
    REMOVE = 2u,
    ALTER = 3u,
    REMOVE_ALL = 4u,
  };


  typedef boost::shared_ptr< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateWorldRequest_

typedef ::giskard_msgs::UpdateWorldRequest_<std::allocator<void> > UpdateWorldRequest;

typedef boost::shared_ptr< ::giskard_msgs::UpdateWorldRequest > UpdateWorldRequestPtr;
typedef boost::shared_ptr< ::giskard_msgs::UpdateWorldRequest const> UpdateWorldRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace giskard_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'giskard_msgs': ['/home/michel/Desktop/suturo/motion/simulation/hsr_ws/src/giskard_msgs/msg', '/home/michel/Desktop/suturo/motion/simulation/hsr_ws/devel/.private/giskard_msgs/share/giskard_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec018c3a5a71401451cb4df98ca2f18a";
  }

  static const char* value(const ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec018c3a5a714014ULL;
  static const uint64_t static_value2 = 0x51cb4df98ca2f18aULL;
};

template<class ContainerAllocator>
struct DataType< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "giskard_msgs/UpdateWorldRequest";
  }

  static const char* value(const ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
uint8 UNDEFINED=0\n\
\n\
\n\
\n\
uint8 ADD=1\n\
\n\
\n\
\n\
uint8 REMOVE=2\n\
\n\
\n\
\n\
uint8 ALTER=3\n\
\n\
\n\
\n\
uint8 REMOVE_ALL=4\n\
\n\
\n\
uint8 operation\n\
\n\
\n\
giskard_msgs/WorldBody body\n\
\n\
\n\
\n\
bool rigidly_attached\n\
\n\
\n\
\n\
\n\
geometry_msgs/PoseStamped pose\n\
\n\
================================================================================\n\
MSG: giskard_msgs/WorldBody\n\
# Representation of a single body into the world \n\
\n\
# Possible constants to fill into the type field\n\
uint8 UNDEFINED=0\n\
uint8 PRIMITIVE_BODY=1\n\
uint8 MESH_BODY=2\n\
uint8 URDF_BODY=3\n\
\n\
# The type of body that is represented\n\
uint8 type\n\
\n\
# The name with which the body shall be addressed in the world\n\
# Note: needs to be unique. If the name is already taken, an error will be returned\n\
string name\n\
\n\
# Only used if type==PRIMITIVE_BODY, otherwise ignored.\n\
shape_msgs/SolidPrimitive shape\n\
\n\
# Only used if type==MESH_BODY, otherwise ignored. \n\
# Needs to be a ROS resource description, like:\n\
# 'package://my_pkg/meshes/some_mesh.dae'\n\
string mesh\n\
\n\
# Only used if type==URDF_BODY, otherwise ignored.\n\
# Needs to comply with the URDF definition from here:\n\
# http://wiki.ros.org/urdf/XML\n\
string urdf\n\
# Only used if type==URDF_BODY, otherwise ignored.\n\
# Optional, can be left empty.\n\
# If not empty, this will interpreted as a ROS topic over which \n\
# message of type sensor_msgs/JointState are communicated that\n\
# contain the current state of all the movable joints described\n\
# in the urdf.\n\
string joint_state_topic\n\
\n\
================================================================================\n\
MSG: shape_msgs/SolidPrimitive\n\
# Define box, sphere, cylinder, cone \n\
# All shapes are defined to have their bounding boxes centered around 0,0,0.\n\
\n\
uint8 BOX=1\n\
uint8 SPHERE=2\n\
uint8 CYLINDER=3\n\
uint8 CONE=4\n\
\n\
# The type of the shape\n\
uint8 type\n\
\n\
\n\
# The dimensions of the shape\n\
float64[] dimensions\n\
\n\
# The meaning of the shape dimensions: each constant defines the index in the 'dimensions' array\n\
\n\
# For the BOX type, the X, Y, and Z dimensions are the length of the corresponding\n\
# sides of the box.\n\
uint8 BOX_X=0\n\
uint8 BOX_Y=1\n\
uint8 BOX_Z=2\n\
\n\
\n\
# For the SPHERE type, only one component is used, and it gives the radius of\n\
# the sphere.\n\
uint8 SPHERE_RADIUS=0\n\
\n\
\n\
# For the CYLINDER and CONE types, the center line is oriented along\n\
# the Z axis.  Therefore the CYLINDER_HEIGHT (CONE_HEIGHT) component\n\
# of dimensions gives the height of the cylinder (cone).  The\n\
# CYLINDER_RADIUS (CONE_RADIUS) component of dimensions gives the\n\
# radius of the base of the cylinder (cone).  Cone and cylinder\n\
# primitives are defined to be circular. The tip of the cone is\n\
# pointing up, along +Z axis.\n\
\n\
uint8 CYLINDER_HEIGHT=0\n\
uint8 CYLINDER_RADIUS=1\n\
\n\
uint8 CONE_HEIGHT=0\n\
uint8 CONE_RADIUS=1\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operation);
      stream.next(m.body);
      stream.next(m.rigidly_attached);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateWorldRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::giskard_msgs::UpdateWorldRequest_<ContainerAllocator>& v)
  {
    s << indent << "operation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operation);
    s << indent << "body: ";
    s << std::endl;
    Printer< ::giskard_msgs::WorldBody_<ContainerAllocator> >::stream(s, indent + "  ", v.body);
    s << indent << "rigidly_attached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rigidly_attached);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GISKARD_MSGS_MESSAGE_UPDATEWORLDREQUEST_H
