(cl:defpackage giskard_msgs-srv
  (:use )
  (:export
   "QUERYMOTION"
   "<QUERYMOTION-REQUEST>"
   "QUERYMOTION-REQUEST"
   "<QUERYMOTION-RESPONSE>"
   "QUERYMOTION-RESPONSE"
   "SETENABLE"
   "<SETENABLE-REQUEST>"
   "SETENABLE-REQUEST"
   "<SETENABLE-RESPONSE>"
   "SETENABLE-RESPONSE"
   "UPDATEWORLD"
   "<UPDATEWORLD-REQUEST>"
   "UPDATEWORLD-REQUEST"
   "<UPDATEWORLD-RESPONSE>"
   "UPDATEWORLD-RESPONSE"
  ))

