// Generated by gencpp from file iai_naive_kinematics_sim/SetJointStateRequest.msg
// DO NOT EDIT!


#ifndef IAI_NAIVE_KINEMATICS_SIM_MESSAGE_SETJOINTSTATEREQUEST_H
#define IAI_NAIVE_KINEMATICS_SIM_MESSAGE_SETJOINTSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace iai_naive_kinematics_sim
{
template <class ContainerAllocator>
struct SetJointStateRequest_
{
  typedef SetJointStateRequest_<ContainerAllocator> Type;

  SetJointStateRequest_()
    : state()  {
    }
  SetJointStateRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointStateRequest_

typedef ::iai_naive_kinematics_sim::SetJointStateRequest_<std::allocator<void> > SetJointStateRequest;

typedef boost::shared_ptr< ::iai_naive_kinematics_sim::SetJointStateRequest > SetJointStateRequestPtr;
typedef boost::shared_ptr< ::iai_naive_kinematics_sim::SetJointStateRequest const> SetJointStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iai_naive_kinematics_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'iai_naive_kinematics_sim': ['/home/michel/Desktop/suturo/motion/simulation/hsr_ws/src/iai_naive_kinematics_sim/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b869e8f6f1d03107da0fd57ef24c9c1d";
  }

  static const char* value(const ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb869e8f6f1d03107ULL;
  static const uint64_t static_value2 = 0xda0fd57ef24c9c1dULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_naive_kinematics_sim/SetJointStateRequest";
  }

  static const char* value(const ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/JointState state\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_naive_kinematics_sim::SetJointStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_NAIVE_KINEMATICS_SIM_MESSAGE_SETJOINTSTATEREQUEST_H
