(cl:defpackage move-msg
  (:use )
  (:export
   "<DOMOVEACTION>"
   "DOMOVEACTION"
   "<DOMOVEACTIONFEEDBACK>"
   "DOMOVEACTIONFEEDBACK"
   "<DOMOVEACTIONGOAL>"
   "DOMOVEACTIONGOAL"
   "<DOMOVEACTIONRESULT>"
   "DOMOVEACTIONRESULT"
   "<DOMOVEFEEDBACK>"
   "DOMOVEFEEDBACK"
   "<DOMOVEGOAL>"
   "DOMOVEGOAL"
   "<DOMOVERESULT>"
   "DOMOVERESULT"
  ))

