; Auto-generated. Do not edit!


(cl:in-package move-msg)


;//! \htmlinclude DoMoveFeedback.msg.html

(cl:defclass <DoMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback_msg
    :reader feedback_msg
    :initarg :feedback_msg
    :type cl:string
    :initform ""))
)

(cl:defclass DoMoveFeedback (<DoMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move-msg:<DoMoveFeedback> is deprecated: use move-msg:DoMoveFeedback instead.")))

(cl:ensure-generic-function 'feedback_msg-val :lambda-list '(m))
(cl:defmethod feedback_msg-val ((m <DoMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move-msg:feedback_msg-val is deprecated.  Use move-msg:feedback_msg instead.")
  (feedback_msg m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoMoveFeedback>) ostream)
  "Serializes a message object of type '<DoMoveFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'feedback_msg))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'feedback_msg))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoMoveFeedback>) istream)
  "Deserializes a message object of type '<DoMoveFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback_msg) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'feedback_msg) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoMoveFeedback>)))
  "Returns string type for a message object of type '<DoMoveFeedback>"
  "move/DoMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoMoveFeedback)))
  "Returns string type for a message object of type 'DoMoveFeedback"
  "move/DoMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoMoveFeedback>)))
  "Returns md5sum for a message object of type '<DoMoveFeedback>"
  "c2d0a7665728d7af4a27ddb9a948c8e6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoMoveFeedback)))
  "Returns md5sum for a message object of type 'DoMoveFeedback"
  "c2d0a7665728d7af4a27ddb9a948c8e6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoMoveFeedback>)))
  "Returns full string definition for message of type '<DoMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define feedback~%string feedback_msg~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoMoveFeedback)))
  "Returns full string definition for message of type 'DoMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define feedback~%string feedback_msg~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoMoveFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'feedback_msg))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DoMoveFeedback
    (cl:cons ':feedback_msg (feedback_msg msg))
))
