; Auto-generated. Do not edit!


(cl:in-package move-msg)


;//! \htmlinclude DoMoveGoal.msg.html

(cl:defclass <DoMoveGoal> (roslisp-msg-protocol:ros-message)
  ((goal_msg
    :reader goal_msg
    :initarg :goal_msg
    :type cl:string
    :initform ""))
)

(cl:defclass DoMoveGoal (<DoMoveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoMoveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoMoveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name move-msg:<DoMoveGoal> is deprecated: use move-msg:DoMoveGoal instead.")))

(cl:ensure-generic-function 'goal_msg-val :lambda-list '(m))
(cl:defmethod goal_msg-val ((m <DoMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader move-msg:goal_msg-val is deprecated.  Use move-msg:goal_msg instead.")
  (goal_msg m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoMoveGoal>) ostream)
  "Serializes a message object of type '<DoMoveGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_msg))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_msg))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoMoveGoal>) istream)
  "Deserializes a message object of type '<DoMoveGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_msg) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_msg) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoMoveGoal>)))
  "Returns string type for a message object of type '<DoMoveGoal>"
  "move/DoMoveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoMoveGoal)))
  "Returns string type for a message object of type 'DoMoveGoal"
  "move/DoMoveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoMoveGoal>)))
  "Returns md5sum for a message object of type '<DoMoveGoal>"
  "27d471430512f085639b52c2950691b4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoMoveGoal)))
  "Returns md5sum for a message object of type 'DoMoveGoal"
  "27d471430512f085639b52c2950691b4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoMoveGoal>)))
  "Returns full string definition for message of type '<DoMoveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%string goal_msg~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoMoveGoal)))
  "Returns full string definition for message of type 'DoMoveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%string goal_msg~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoMoveGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_msg))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoMoveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoMoveGoal
    (cl:cons ':goal_msg (goal_msg msg))
))
