// Generated by gencpp from file move/DoMoveFeedback.msg
// DO NOT EDIT!


#ifndef MOVE_MESSAGE_DOMOVEFEEDBACK_H
#define MOVE_MESSAGE_DOMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move
{
template <class ContainerAllocator>
struct DoMoveFeedback_
{
  typedef DoMoveFeedback_<ContainerAllocator> Type;

  DoMoveFeedback_()
    : feedback_msg()  {
    }
  DoMoveFeedback_(const ContainerAllocator& _alloc)
    : feedback_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_msg_type;
  _feedback_msg_type feedback_msg;





  typedef boost::shared_ptr< ::move::DoMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move::DoMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DoMoveFeedback_

typedef ::move::DoMoveFeedback_<std::allocator<void> > DoMoveFeedback;

typedef boost::shared_ptr< ::move::DoMoveFeedback > DoMoveFeedbackPtr;
typedef boost::shared_ptr< ::move::DoMoveFeedback const> DoMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move::DoMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move::DoMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'move': ['/home/michel/Desktop/suturo/motion/simulation/hsr_ws/devel/.private/move/share/move/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::move::DoMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move::DoMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::DoMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::DoMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::DoMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::DoMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move::DoMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2d0a7665728d7af4a27ddb9a948c8e6";
  }

  static const char* value(const ::move::DoMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2d0a7665728d7afULL;
  static const uint64_t static_value2 = 0x4a27ddb9a948c8e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::move::DoMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move/DoMoveFeedback";
  }

  static const char* value(const ::move::DoMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move::DoMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# define feedback\n\
string feedback_msg\n\
\n\
";
  }

  static const char* value(const ::move::DoMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move::DoMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move::DoMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move::DoMoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_MESSAGE_DOMOVEFEEDBACK_H
